# Arquivo: .rubocop.yml

AllCops:
  # Desativa todos os Cops por padrão
  DisabledByDefault: true
  
  # Exclui explicitamente todos os arquivos do projeto da verificação
  Exclude:
    - '**/*'

  # Mantém esta linha para silenciar os avisos sobre novas regras,
  # mesmo que o linter não esteja rodando em nenhum arquivo.
  NewCops: enable

# A regra de documentação não precisa mais ser desativada explicitamente, 
# pois DisabledByDefault: true cuida disso.